commands:
  pe2:
    - cmd: sysctl -w net.mpls.conf.lo.input=1 > /dev/null
    - cmd: sysctl -w net.mpls.conf.net12.input=1 > /dev/null
    - cmd: sysctl -w net.mpls.platform_labels=1024 > /dev/null
    - cmd: >-
        vtysh -c 'conf t'
        -c 'interface lo'
        -c ' ip addr 12.12.12.12/32'
        -c ' ip ospf passive'
        -c 'exit'
        -c 'router ospf'
        -c ' ospf router-id 12.12.12.12'
        -c ' network 12.12.12.12/32 area 0.0.0.0'
        -c ' network 172.16.12.0/24 area 0.0.0.0'
        -c 'exit'
        -c 'mpls ldp'
        -c ' router-id 12.12.12.12'
        -c ' address-family ipv4'
        -c '  discovery transport-address 12.12.12.12'
        -c '  interface lo'
        -c '  interface net12'
        -c 'exit'
    - cmd: ip link add VPN-A type vrf table 10
    - cmd: ip link set VPN-A up
    - cmd: ip link set net114 vrf VPN-A
    - cmd: >-
        vtysh -c 'conf t'
        -c 'ip route 192.168.0.0/24 172.16.114.114 vrf VPN-A'
    - cmd: >-
        vtysh -c 'conf t'
        -c 'router bgp 65000'
        -c ' neighbor 11.11.11.11 remote-as 65000'
        -c ' neighbor 11.11.11.11 update-source 12.12.12.12'
        -c ' neighbor 13.13.13.13 remote-as 65000'
        -c ' neighbor 13.13.13.13 update-source 12.12.12.12'
        -c ' address-family ipv4 vpn'
        -c '  neighbor 11.11.11.11 activate'
        -c '  neighbor 13.13.13.13 activate'
        -c 'exit'
    - cmd: >-
        vtysh -c 'conf t'
        -c 'router bgp 65000 vrf VPN-A'
        -c ' address-family ipv4 unicast'
        -c '  label vpn export auto'
        -c '  redistribute static'
        -c '  rd vpn export 65000:1'
        -c '  rt vpn both 65000:100'
        -c '  import vpn'
        -c '  export vpn'
        -c 'exit'