commands:
  router3:
    - cmd: sysctl -w net.mpls.conf.lo.input=1 > /dev/null
    - cmd: sysctl -w net.mpls.conf.net2.input=1 > /dev/null
    - cmd: sysctl -w net.mpls.conf.net3.input=1 > /dev/null
    - cmd: sysctl -w net.mpls.conf.net5.input=1 > /dev/null
    - cmd: sysctl -w net.mpls.platform_labels=1024 > /dev/null
#    - cmd: >-
#        vtysh -c 'conf t'
#        -c 'interface lo'
#        -c ' ip addr 3.3.3.3/32'
#        -c 'exit'
#        -c 'router ospf'
#        -c ' network 3.3.3.3/32 area 0.0.0.0'
#        -c ' network 172.16.2.0/24 area 0.0.0.0'
#        -c ' network 172.16.3.0/24 area 0.0.0.0'
#        -c ' network 172.16.5.0/24 area 0.0.0.0'
#        -c 'exit'
    - cmd: ip -M route add 101 via inet 172.16.5.4
    - cmd: ip -M route add 201 via inet 172.16.2.1