commands:
  ce4:
    - cmd: >-
        vtysh -c 'conf t'
        -c 'log file /var/log/frr/frr.log'
        -c 'interface lo'
        -c ' ip addr 114.114.114.114/32'
        -c 'exit'
        -c 'ip route 0.0.0.0/0 172.16.114.12'
        -c 'ip route 111.111.111.111/32 172.16.114.12'
        -c 'ip route 112.112.112.112/32 172.16.114.12'
        -c 'ip route 115.115.115.115/32 172.16.114.12'
    # create vrf
    - cmd: ip link add VPN-A-1 type vrf table 100
    - cmd: ip link set VPN-A-1 up
    # create br0
    - cmd: ip link add br0 type bridge vlan_filtering 1
    - cmd: ip link set dev br0 up
    # create vxlan100
    - cmd: ip link add vxlan100 type vxlan nolearning dstport 4789 id 100 local 114.114.114.114
    - cmd: ip link set dev vxlan100 master br0
    - cmd: bridge vlan add vid 100 dev br0 self
    - cmd: bridge vlan add vid 100 dev vxlan100 untagged pvid
    - cmd: ip link set dev vxlan100 promisc on
    - cmd: ip link set dev vxlan100 mtu 9000
    - cmd: ip link set dev vxlan100 up
    - cmd: ip link add link br0 name br0.100 type vlan id 100
    - cmd: ip link set dev br0.100 mtu 9000
    - cmd: ip link set dev br0.100 up
    - cmd: ip link set br0.100 vrf VPN-A-1
    # create vxlan101
    - cmd: ip link add vxlan101 type vxlan nolearning dstport 4789 id 101 local 114.114.114.114
    - cmd: ip link set dev vxlan101 master br0
    - cmd: bridge vlan add vid 101 dev br0 self
    - cmd: bridge vlan add vid 101 dev vxlan101 untagged pvid
    - cmd: ip link set dev vxlan101 promisc on
    - cmd: ip link set dev vxlan101 mtu 9000
    - cmd: ip link set dev vxlan101 up
    - cmd: ip link add link br0 name br0.101 type vlan id 101
    - cmd: ip link set dev br0.101 mtu 9000   
    - cmd: ip link set dev br0.101 up
    - cmd: ip addr add 10.0.0.1/24 dev br0.101
    - cmd: ip link set br0.101 vrf VPN-A-1
    # create vxlan102  
    - cmd: ip link add vxlan102 type vxlan nolearning dstport 4789 id 102 local 114.114.114.114
    - cmd: ip link set dev vxlan102 master br0
    - cmd: bridge vlan add vid 102 dev br0 self
    - cmd: bridge vlan add vid 102 dev vxlan102 untagged pvid
    - cmd: ip link set dev vxlan102 promisc on
    - cmd: ip link set dev vxlan102 mtu 9000
    - cmd: ip link set dev vxlan102 up
    - cmd: ip link add link br0 name br0.102 type vlan id 102
    - cmd: ip link set dev br0.102 mtu 9000   
    - cmd: ip link set dev br0.102 up
    - cmd: ip addr add 10.0.1.1/24 dev br0.102
    - cmd: ip link set br0.102 vrf VPN-A-1
    # create vxlan103
    - cmd: ip link add vxlan103 type vxlan nolearning dstport 4789 id 103 local 114.114.114.114
    - cmd: ip link set dev vxlan103 master br0
    - cmd: bridge vlan add vid 103 dev br0 self
    - cmd: bridge vlan add vid 103 dev vxlan103 untagged pvid
    - cmd: ip link set dev vxlan103 promisc on
    - cmd: ip link set dev vxlan103 mtu 9000
    - cmd: ip link set dev vxlan103 up
    - cmd: ip link add link br0 name br0.103 type vlan id 103
    - cmd: ip link set dev br0.103 mtu 9000   
    - cmd: ip link set dev br0.103 up
    - cmd: ip addr add 192.168.0.1/24 dev br0.103
    - cmd: ip link set br0.103 vrf VPN-A-1
    # create netns h4-1,h4-2,h4-3
    - cmd: ip netns add h4-1
    - cmd: ip netns add h4-2
    - cmd: ip netns add h4-3
    - cmd: ip link add h4-1-veth0 netns h4-1 type veth peer name ce3-veth0
    - cmd: ip link add h4-2-veth0 netns h4-2 type veth peer name ce3-veth1
    - cmd: ip link add h4-3-veth0 netns h4-3 type veth peer name ce3-veth2
    - cmd: ip netns exec h4-1 ip addr add 10.0.0.14/24 dev h4-1-veth0
    - cmd: ip netns exec h4-2 ip addr add 10.0.1.14/24 dev h4-2-veth0
    - cmd: ip netns exec h4-3 ip addr add 192.168.0.14/24 dev h4-3-veth0
    - cmd: ip netns exec h4-1 ip link set dev h4-1-veth0 up
    - cmd: ip netns exec h4-2 ip link set dev h4-2-veth0 up
    - cmd: ip netns exec h4-3 ip link set dev h4-3-veth0 up
    - cmd: ip netns exec h4-1 ip route add default via 10.0.0.1
    - cmd: ip netns exec h4-2 ip route add default via 10.0.1.1
    - cmd: ip netns exec h4-3 ip route add default via 192.168.0.1
    - cmd: ip link set dev ce3-veth0 master br0
    - cmd: ip link set dev ce3-veth1 master br0
    - cmd: ip link set dev ce3-veth2 master br0
    - cmd: ip link set dev ce3-veth0 promisc on
    - cmd: ip link set dev ce3-veth0 promisc on
    - cmd: ip link set dev ce3-veth0 up
    - cmd: ip link set dev ce3-veth1 up
    - cmd: ip link set dev ce3-veth2 up
    - cmd: bridge vlan add vid 101 dev ce3-veth0 untagged pvid
    - cmd: bridge vlan add vid 102 dev ce3-veth1 untagged pvid
    - cmd: bridge vlan add vid 103 dev ce3-veth2 untagged pvid
    - cmd: >-
        vtysh -c 'conf t'
        -c 'vrf VPN-A-1'
        -c ' vni 100'
    - cmd: >-
        vtysh -c 'conf t'
        -c 'router bgp 65001'
        -c ' bgp router-id 114.114.114.114'
        -c ' no bgp default ipv4-unicast'
        -c ' neighbor evpn-peer peer-group'
        -c ' neighbor evpn-peer remote-as 65001'
        -c ' neighbor evpn-peer update-source 114.114.114.114'
        -c ' neighbor evpn-peer capability extended-nexthop'
        -c ' neighbor 111.111.111.111 peer-group evpn-peer'
        -c ' neighbor 112.112.112.112 peer-group evpn-peer'
        -c ' neighbor 115.115.115.115 peer-group evpn-peer'
        -c ' address-family ipv4 unicast'
        -c '  neighbor evpn-peer activate'
        -c '  neighbor evpn-peer soft-reconfiguration inbound'
        -c ' address-family l2vpn evpn'
        -c '  neighbor evpn-peer activate'
        -c '  advertise-all-vni'
        -c 'exit'