commands:
  p1:
    - cmd: sysctl -w net.mpls.conf.lo.input=1 > /dev/null
    - cmd: sysctl -w net.mpls.conf.net1.input=1 > /dev/null
    - cmd: sysctl -w net.mpls.conf.net2.input=1 > /dev/null
    - cmd: sysctl -w net.mpls.conf.net11.input=1 > /dev/null
    - cmd: sysctl -w net.mpls.conf.net12.input=1 > /dev/null
    - cmd: sysctl -w net.mpls.platform_labels=1024 > /dev/null
    - cmd: >-
        vtysh -c 'conf t'
        -c 'interface lo'
        -c ' ip addr 1.1.1.1/32'
        -c ' ip ospf passive'
        -c 'exit'
        -c 'router ospf'
        -c ' ospf router-id 1.1.1.1'
        -c ' network 1.1.1.1/32 area 0.0.0.0'
        -c ' network 172.16.1.0/24 area 0.0.0.0'
        -c ' network 172.16.2.0/24 area 0.0.0.0'
        -c ' network 172.16.11.0/24 area 0.0.0.0'
        -c ' network 172.16.12.0/24 area 0.0.0.0'
        -c 'exit'
        -c 'mpls ldp'
        -c ' router-id 1.1.1.1'
        -c ' address-family ipv4'
        -c '  discovery transport-address 1.1.1.1'
        -c '  interface lo'
        -c '  interface net1'
        -c '  interface net2'
        -c '  interface net11'
        -c '  interface net12'
        -c 'exit'